-- Supabase Schema: accounts.sql

-- Table Definition: accounts
CREATE TABLE IF NOT EXISTS "public"."accounts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" UNIQUE NOT NULL,
    "subscription_id" bigint DEFAULT '1'::bigint NOT NULL,
    "subscription_expiration_date" timestamp with time zone
);
ALTER TABLE "public"."accounts" OWNER TO "postgres";
ALTER TABLE ONLY "public"."accounts"
    ADD CONSTRAINT "accounts_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."accounts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."accounts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
-- Foreign key to subscription_tiers will be added in subscription_tiers.sql to avoid circular dependencies if accounts.id is also a FK there.
-- However, typically subscription_id in accounts would point to subscription_tiers.id
-- Assuming: ALTER TABLE "public"."accounts" ADD CONSTRAINT "accounts_subscription_id_fkey" FOREIGN KEY ("subscription_id") REFERENCES "public"."subscription_tiers"("id");

-- Table Definition: accounts_addresses (from 20240915211603_inital_schema.sql)
CREATE TABLE IF NOT EXISTS "public"."accounts_addresses" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "address" "text" NOT NULL,
    "name" "text",
    "account_id" bigint NOT NULL
);
ALTER TABLE "public"."accounts_addresses" OWNER TO "postgres";
ALTER TABLE ONLY "public"."accounts_addresses"
    ADD CONSTRAINT "accounts_addresses_pkey" PRIMARY KEY ("address");
ALTER TABLE ONLY "public"."accounts_addresses"
    ADD CONSTRAINT "accounts_addresses_address_key" UNIQUE ("address");
ALTER TABLE ONLY "public"."accounts_addresses"
    ADD CONSTRAINT "accounts_addresses_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE;

-- Table Definition: accounts_api_keys (from 20240915211603_inital_schema.sql)
CREATE TABLE IF NOT EXISTS "public"."accounts_api_keys" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "key" "text" NOT NULL,
    "account_id" bigint NOT NULL,
    "origin" "text" NOT NULL,
    "is_dev" boolean DEFAULT false
);
ALTER TABLE "public"."accounts_api_keys" OWNER TO "postgres";
ALTER TABLE ONLY "public"."accounts_api_keys"
    ADD CONSTRAINT "accounts_api_keys_pkey" PRIMARY KEY ("key");
ALTER TABLE ONLY "public"."accounts_api_keys"
    ADD CONSTRAINT "accounts_api_keys_key_key" UNIQUE ("key");
ALTER TABLE ONLY "public"."accounts_api_keys"
    ADD CONSTRAINT "accounts_api_keys_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS "public"."accounts_users_association" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "account_id" bigint NOT NULL,
    "user_email" "text" NOT NULL,
    "role" "public"."accounts_users_roles" NOT NULL,
    CONSTRAINT "accounts_users_association_pkey" PRIMARY KEY ("account_id", "user_email"),
    CONSTRAINT "accounts_users_association_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE
);
ALTER TABLE "public"."accounts_users_association" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."accounts_chains_parameters" (
    "account_id" bigint NOT NULL,
    "chain_id" text NOT NULL, -- Foreign key to chains.id
    "enable_secondary" boolean NOT NULL DEFAULT false,
    "secondary_percentage_fee" float NOT NULL DEFAULT 0,
    "secondary_fee_address" text,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "accounts_chains_parameters_pkey" PRIMARY KEY ("account_id", "chain_id"),
    CONSTRAINT "accounts_chains_parameters_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE,
    CONSTRAINT "accounts_chains_parameters_chain_id_fkey" FOREIGN KEY ("chain_id") REFERENCES "public"."chains"("id") ON DELETE CASCADE
);
ALTER TABLE "public"."accounts_chains_parameters" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."accounts_currencies" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "account_id" bigint NOT NULL,
    "currency" "text" NOT NULL,
    "chain_id" text NOT NULL,
    CONSTRAINT "accounts_currencies_pkey" PRIMARY KEY ("account_id", "currency", "chain_id"),
    CONSTRAINT "accounts_currencies_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE CASCADE,
    CONSTRAINT "accounts_currencies_chain_id_fkey" FOREIGN KEY ("currency", "chain_id") REFERENCES "public"."currencies"("id", "chain_id") ON DELETE CASCADE
);
ALTER TABLE "public"."accounts_currencies" OWNER TO "postgres";

-- RLS Policies for accounts and related tables (from 20240915211603_inital_schema.sql)
ALTER TABLE "public"."accounts" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to all accounts" ON "public"."accounts" FOR SELECT USING (true);
CREATE POLICY "Users can insert their own account" ON "public"."accounts" FOR INSERT WITH CHECK (auth.email() = owner_email);
CREATE POLICY "Owner can update account settings" ON "public"."accounts" FOR UPDATE USING (auth.email() = owner_email);
CREATE POLICY "Owner and admins can update account settings" ON "public"."accounts" FOR UPDATE TO "authenticated" USING (("id" IN ( SELECT "private"."get_administrated_accounts_for_user"("auth"."email"()) AS "get_administrated_accounts_for_user")));
CREATE POLICY "Owner can delete account" ON "public"."accounts" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."email"() AS "email") = "owner_email"));

ALTER TABLE "public"."accounts_addresses" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Account members can view addresses" ON "public"."accounts_addresses" FOR SELECT USING (("account_id" IN ( SELECT "private"."get_member_accounts_for_user"("auth"."email"()) AS "get_member_accounts_for_user")));
CREATE POLICY "Account admins can manage addresses" ON "public"."accounts_addresses" FOR ALL USING (("account_id" IN ( SELECT "private"."get_administrated_accounts_for_user"("auth"."email"()) AS "get_administrated_accounts_for_user")));

-- RLS for accounts_api_keys
ALTER TABLE "public"."accounts_api_keys" ENABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE "public"."accounts_api_keys" TO "authenticated";
GRANT ALL ON TABLE "public"."accounts_api_keys" TO "service_role";
CREATE POLICY "Account members can view API keys" ON "public"."accounts_api_keys" FOR SELECT USING (("account_id" IN ( SELECT "private"."get_member_accounts_for_user"("auth"."email"()) AS "get_member_accounts_for_user")));
CREATE POLICY "Account admins can manage API keys" ON "public"."accounts_api_keys" FOR ALL USING (("account_id" IN ( SELECT "private"."get_administrated_accounts_for_user"("auth"."email"()) AS "get_administrated_accounts_for_user")));

-- RLS for accounts_currencies
ALTER TABLE "public"."accounts_currencies" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE "public"."accounts_currencies" TO "anon";
GRANT ALL ON TABLE "public"."accounts_currencies" TO "authenticated";
GRANT ALL ON TABLE "public"."accounts_currencies" TO "service_role";
CREATE POLICY "Public can view account currencies" ON "public"."accounts_currencies" FOR SELECT USING (true);
CREATE POLICY "Account admins can manage account currencies" ON "public"."accounts_currencies" FOR ALL USING (SELECT "private"."is_user_account_admin"("auth"."email"(), "account_id"));

-- RLS for accounts_users_association
ALTER TABLE "public"."accounts_users_association" ENABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE "public"."accounts_users_association" TO "authenticated";
GRANT ALL ON TABLE "public"."accounts_users_association" TO "service_role";
CREATE POLICY "Account members can view users in their account" ON "public"."accounts_users_association" FOR SELECT USING (SELECT "private"."is_user_account_member"("auth"."email"(), "account_id"));
CREATE POLICY "Account admins can manage account users" ON "public"."accounts_users_association" FOR ALL USING (SELECT "private"."is_user_account_admin"("auth"."email"(), "account_id"));

-- RLS for accounts_chains_parameters
ALTER TABLE "public"."accounts_chains_parameters" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE "public"."accounts_chains_parameters" TO "anon";
GRANT ALL ON TABLE "public"."accounts_chains_parameters" TO "authenticated"; 
GRANT ALL ON TABLE "public"."accounts_chains_parameters" TO "service_role";
CREATE POLICY "Public can view chain parameters" ON "public"."accounts_chains_parameters" FOR SELECT USING (true);
CREATE POLICY "Account admins can manage accounts chain parameters" ON "public"."accounts_chains_parameters" FOR ALL USING (SELECT "private"."is_user_account_admin"("auth"."email"(), "account_id"));

-- Functions related to accounts
CREATE OR REPLACE FUNCTION "private"."is_user_account_owner"("user_email" "text", "account_id" "bigint") RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
        AS $_$
        SELECT EXISTS (
            SELECT 1 
            FROM "public"."accounts_users_association" 
            WHERE user_email = $1 
            AND account_id = $2 
            AND role = 'owner'
        );
    $_$;
ALTER FUNCTION "private"."is_user_account_owner"("user_email" "text", "account_id" "bigint") OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "private"."is_user_account_admin"("user_email" "text", "account_id" "bigint") RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
        AS $_$
        SELECT EXISTS (
            SELECT 1 
            FROM "public"."accounts_users_association" 
            WHERE user_email = $1 
            AND account_id = $2 
            AND role IN ('owner', 'admin')
        );
    $_$;
ALTER FUNCTION "private"."is_user_account_admin"("user_email" "text", "account_id" "bigint") OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "private"."is_user_account_member"("user_email" "text", "account_id" "bigint") RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
        AS $_$
        SELECT EXISTS (
            SELECT 1 
            FROM "public"."accounts_users_association" 
            WHERE user_email = $1 
            AND account_id = $2
            AND role IN ('owner', 'admin', 'member')
    );
    $_$;
ALTER FUNCTION "private"."is_user_account_member"("user_email" "text", "account_id" "bigint") OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "private"."get_user_accounts"("user_email" "text") RETURNS SETOF bigint
    LANGUAGE "sql" STABLE SECURITY DEFINER
    AS $_$select account_id from public.accounts_users_association where user_email = $1$_$;
ALTER FUNCTION "private"."get_user_accounts"("user_email" "text") OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."get_key_account_id"("key" "text", "origin" "text") RETURNS bigint
    LANGUAGE "sql" STABLE SECURITY DEFINER
    AS $_$select account_id from "public"."accounts_api_keys" where key::text = $1 and origin = $2$_$;
ALTER FUNCTION "public"."get_key_account_id"("key" "text", "origin" "text") OWNER TO "postgres";

-- Grant permissions for functions
GRANT EXECUTE ON FUNCTION "private"."is_user_account_owner"("user_email" "text", "account_id" "bigint") TO "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "private"."is_user_account_admin"("user_email" "text", "account_id" "bigint") TO "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "private"."is_user_account_member"("user_email" "text", "account_id" "bigint") TO "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "private"."get_user_accounts"("user_email" "text") TO "authenticated", "service_role";
GRANT EXECUTE ON FUNCTION "public"."get_key_account_id"("key" "text", "origin" "text") TO "anon", "authenticated", "service_role";
