-- Supabase Schema: dutch_auctions.sql

CREATE TABLE IF NOT EXISTS "public"."dutch_auctions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone,
    "listing_id" "uuid" NOT NULL,
    "min_price" double precision NOT NULL,
    "max_price" double precision,
    "duration" integer NOT NULL
);

ALTER TABLE "public"."dutch_auctions" OWNER TO "postgres";

ALTER TABLE "public"."dutch_auctions" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."dutch_auctions_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Primary Key
ALTER TABLE ONLY "public"."dutch_auctions"
    ADD CONSTRAINT "dutch_auctions_pkey" PRIMARY KEY ("id");

-- Foreign Keys
ALTER TABLE ONLY "public"."dutch_auctions"
    ADD CONSTRAINT "public_dutch_auctions_listing_id_fkey" FOREIGN KEY ("listing_id") REFERENCES "public"."listings"("id") ON DELETE CASCADE;

-- Indexes
CREATE INDEX "idx_dutch_auctions" ON "public"."dutch_auctions" USING "btree" ("listing_id");

-- RLS Policies (from 20240915211603_inital_schema.sql)
ALTER TABLE "public"."dutch_auctions" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for API keys" ON "public"."dutch_auctions" FOR SELECT USING (("listing_id" IN ( SELECT "listings"."id"
   FROM "public"."listings"
  WHERE ("listings"."account_id" = ( SELECT "public"."get_key_account_id"((("current_setting"('request.headers'::"text", true))::"json" ->> 'x-arcpay-key'::"text"), (("current_setting"('request.headers'::"text", true))::"json" ->> 'origin'::"text")) AS "get_key_account_id")))));

CREATE POLICY "Enable write access for API keys" ON "public"."dutch_auctions" FOR INSERT WITH CHECK (("listing_id" IN ( SELECT "listings"."id"
   FROM "public"."listings"
  WHERE ("listings"."account_id" = ( SELECT "public"."get_key_account_id"((("current_setting"('request.headers'::"text", true))::"json" ->> 'x-arcpay-key'::"text"), (("current_setting"('request.headers'::"text", true))::"json" ->> 'origin'::"text")) AS "get_key_account_id")))));

CREATE POLICY "Members can manage dutch auctions" ON "public"."dutch_auctions" TO "authenticated" USING (("listing_id" IN ( SELECT "listings"."id"
   FROM "public"."listings"
  WHERE ("listings"."account_id" IN ( SELECT "private"."get_member_accounts_for_user"("auth"."email"()) AS "get_member_accounts_for_user")))));

-- Grants (from 20240915211603_inital_schema.sql)
GRANT ALL ON TABLE "public"."dutch_auctions" TO "anon";
GRANT ALL ON TABLE "public"."dutch_auctions" TO "authenticated";
GRANT ALL ON TABLE "public"."dutch_auctions" TO "service_role";

GRANT ALL ON SEQUENCE "public"."dutch_auctions_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dutch_auctions_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dutch_auctions_id_seq" TO "service_role";
