/*
# Subscription Tiers Schema Permissions Table

This table provides a comprehensive overview of permissions for different user roles across all tables in the subscription tiers schema.

| Table                           | anon               | authenticated       | member              | admin               | owner               |
|---------------------------------|--------------------|---------------------|---------------------|---------------------|---------------------|
| subscription_tiers              | SELECT (read-only) | SELECT (read-only)  | SELECT (read-only)  | SELECT (read-only)  | SELECT (read-only)  |
| subscriptions_chains_parameters | SELECT (read-only) | SELECT (read-only)  | SELECT (read-only)  | SELECT (read-only)  | SELECT (read-only)  |

## Function Permissions
| Function                       | anon               | authenticated       | member              | admin               | owner               |
|--------------------------------|--------------------|---------------------|---------------------|---------------------|---------------------|
| get_account_subscription_params| EXECUTE            | EXECUTE             | EXECUTE             | EXECUTE             | EXECUTE             |

## Notes:
- "authenticated" refers to any logged-in user
- "member", "admin", and "owner" are roles assigned to authenticated users within specific accounts
- RLS (Row-Level Security) policies enforce access at the row level
- Subscription tiers are read-only for all user types (managed by administrators)
- The service_role has ALL permissions on all tables (superuser)
*/

-------------------- TYPES --------------------
CREATE TYPE "public"."chain_subscription_parameters" AS (
    allow_secondary_listings boolean,
    allow_custom_currencies boolean,
    flat_fees float,
    sales_fees float,
    secondary_flat_fees float,
    secondary_sales_fees float
);

-------------------- SUBSCRIPTION_TIERS --------------------
CREATE TABLE IF NOT EXISTS "public"."subscription_tiers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "duration" bigint, 
    "allow_secondary_listings" boolean NOT NULL DEFAULT false,
    "allow_custom_currencies" boolean NOT NULL DEFAULT false,
    CONSTRAINT "subscription_tiers_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."subscription_tiers" OWNER TO "postgres";

ALTER TABLE "public"."subscription_tiers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."subscription_tiers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- RLS for subscription_tiers
ALTER TABLE "public"."subscription_tiers" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE "public"."subscription_tiers" TO "anon";
GRANT SELECT ON TABLE "public"."subscription_tiers" TO "authenticated";
GRANT ALL ON TABLE "public"."subscription_tiers" TO "service_role";

GRANT SELECT ON SEQUENCE "public"."subscription_tiers_id_seq" TO "anon";
GRANT SELECT ON SEQUENCE "public"."subscription_tiers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."subscription_tiers_id_seq" TO "service_role";

CREATE POLICY "Enable read access for all users" ON "public"."subscription_tiers" FOR SELECT USING (true);


-------------------- SUBSCRIPTION_CHAINS_PARAMETERS --------------------
CREATE TABLE IF NOT EXISTS "public"."subscriptions_chains_parameters" (
    "subscription_id" bigint NOT NULL,
    "chain_id" "text" NOT NULL,
    "flat_fees" float NOT NULL DEFAULT 10,
    "sales_fees" float NOT NULL DEFAULT 0,
    "secondary_flat_fees" float NOT NULL DEFAULT 20,
    "secondary_sales_fees" float NOT NULL DEFAULT 0,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "subscriptions_chains_parameters_pkey" PRIMARY KEY ("subscription_id", "chain_id"),
    CONSTRAINT "subscriptions_chains_parameters_subscription_id_fkey" FOREIGN KEY ("subscription_id") REFERENCES "public"."subscription_tiers"("id") ON DELETE CASCADE,
    CONSTRAINT "subscriptions_chains_parameters_chain_id_fkey" FOREIGN KEY ("chain_id") REFERENCES "public"."chains"("id") ON DELETE CASCADE
);
ALTER TABLE "public"."subscriptions_chains_parameters" OWNER TO "postgres";

-- RLS for subscriptions_chains_parameters
ALTER TABLE "public"."subscriptions_chains_parameters" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE "public"."subscriptions_chains_parameters" TO "anon";
GRANT SELECT ON TABLE "public"."subscriptions_chains_parameters" TO "authenticated";
GRANT ALL ON TABLE "public"."subscriptions_chains_parameters" TO "service_role";

CREATE POLICY "Enable read access for all users" ON "public"."subscriptions_chains_parameters" FOR SELECT USING (true);


-------------------- FUNCTIONS --------------------
CREATE OR REPLACE FUNCTION "public"."get_account_subscription_params"("p_account_id" "uuid", "p_chain_id" "text")
RETURNS "public"."chain_subscription_parameters"
LANGUAGE "sql" STABLE SECURITY DEFINER
SET search_path = ''
AS $_$
    SELECT st.allow_secondary_listings, st.allow_custom_currencies, scp.flat_fees, scp.sales_fees, scp.secondary_flat_fees, scp.secondary_sales_fees
    FROM "public"."subscription_tiers" st
    JOIN "public"."accounts" a ON st.id = a.subscription_id
    JOIN "public"."subscriptions_chains_parameters" scp ON st.id = scp.subscription_id AND scp.chain_id = p_chain_id
    WHERE a.id = p_account_id;
$_$;

ALTER FUNCTION "public"."get_account_subscription_params"("uuid", "p_chain_id" "text") OWNER TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_account_subscription_params"("uuid", "p_chain_id" "text") TO "anon", "authenticated", "service_role";