/*
# Subscription Tiers Schema Permissions Table

This table provides a comprehensive overview of permissions for different user roles across all tables in the subscription tiers schema.

| Table                           | anon               | authenticated       | member              | admin               | owner               |
|---------------------------------|--------------------|---------------------|---------------------|---------------------|---------------------|
| subscription_tiers              | SELECT (read-only) | SELECT (read-only)  | SELECT (read-only)  | SELECT (read-only)  | SELECT (read-only)  |
| subscriptions_networks_parameters | SELECT (read-only) | SELECT (read-only)  | SELECT (read-only)  | SELECT (read-only)  | SELECT (read-only)  |

## Function Permissions
| Function                       | anon               | authenticated       | member              | admin               | owner               |
|--------------------------------|--------------------|---------------------|---------------------|---------------------|---------------------|
| get_account_subscription_params| EXECUTE            | EXECUTE             | EXECUTE             | EXECUTE             | EXECUTE             |

## Notes:
- "authenticated" refers to any logged-in user
- "member", "admin", and "owner" are roles assigned to authenticated users within specific accounts
- RLS (Row-Level Security) policies enforce access at the row level
- Subscription tiers are read-only for all user types (managed by administrators)
- The service_role has ALL permissions on all tables (superuser)
*/

-------------------- TYPES --------------------
CREATE TYPE "public"."network_subscription_parameters" AS (
    allow_secondary_listings boolean,
    allow_custom_assets boolean,
    flat_fees float,
    sales_fees float,
    secondary_flat_fees float,
    secondary_sales_fees float
);

-------------------- SUBSCRIPTION_TIERS --------------------
CREATE TABLE IF NOT EXISTS "public"."subscription_tiers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "duration" bigint, 
    "allow_secondary_listings" boolean NOT NULL DEFAULT false,
    "allow_custom_assets" boolean NOT NULL DEFAULT false,
    CONSTRAINT "subscription_tiers_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."subscription_tiers" OWNER TO "postgres";

ALTER TABLE "public"."subscription_tiers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."subscription_tiers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- RLS for subscription_tiers
ALTER TABLE "public"."subscription_tiers" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE "public"."subscription_tiers" TO "anon";
GRANT SELECT ON TABLE "public"."subscription_tiers" TO "authenticated";
GRANT ALL ON TABLE "public"."subscription_tiers" TO "service_role";

GRANT SELECT ON SEQUENCE "public"."subscription_tiers_id_seq" TO "anon";
GRANT SELECT ON SEQUENCE "public"."subscription_tiers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."subscription_tiers_id_seq" TO "service_role";

CREATE POLICY "Enable read access for all users" ON "public"."subscription_tiers" FOR SELECT USING (true);


-------------------- SUBSCRIPTION_NETWORKS_PARAMETERS --------------------
CREATE TABLE IF NOT EXISTS "public"."subscriptions_networks_parameters" (
    "subscription_id" bigint NOT NULL,
    "network_id" "text" NOT NULL,
    "flat_fees" float NOT NULL DEFAULT 10,
    "sales_fees" float NOT NULL DEFAULT 0,
    "secondary_flat_fees" float NOT NULL DEFAULT 20,
    "secondary_sales_fees" float NOT NULL DEFAULT 0,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "subscriptions_networks_parameters_pkey" PRIMARY KEY ("subscription_id", "network_id"),
    CONSTRAINT "subscriptions_networks_parameters_subscription_id_fkey" FOREIGN KEY ("subscription_id") REFERENCES "public"."subscription_tiers"("id") ON DELETE CASCADE,
    CONSTRAINT "subscriptions_networks_parameters_network_id_fkey" FOREIGN KEY ("network_id") REFERENCES "public"."networks"("id") ON DELETE CASCADE
);
ALTER TABLE "public"."subscriptions_networks_parameters" OWNER TO "postgres";

-- RLS for subscriptions_networks_parameters
ALTER TABLE "public"."subscriptions_networks_parameters" ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON TABLE "public"."subscriptions_networks_parameters" TO "anon";
GRANT SELECT ON TABLE "public"."subscriptions_networks_parameters" TO "authenticated";
GRANT ALL ON TABLE "public"."subscriptions_networks_parameters" TO "service_role";

CREATE POLICY "Enable read access for all users" ON "public"."subscriptions_networks_parameters" FOR SELECT USING (true);