-- Supabase Schema: subscription_tiers.sql

-- Table Definition: subscription_tiers
-- Source: Derived from migrations 20240915211603_inital_schema.sql and 20250413025414_updated_accounts.sql
CREATE TABLE IF NOT EXISTS "public"."subscription_tiers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "duration" bigint, -- Duration of the subscription tier, e.g., in days. NULL might mean indefinite.
    -- Fields added in 20250413025414_updated_accounts.sql
    "allow_secondary_listings" boolean NOT NULL DEFAULT false,
    "allow_custom_currencies" boolean NOT NULL DEFAULT false
    -- Fields like listing_flat_fee, sale_percentage_fee, etc., were dropped in 20250413025414
    -- as they are now managed in the subscriptions_chains_parameters table.
);

-- Set ownership
ALTER TABLE "public"."subscription_tiers" OWNER TO "postgres";

-- Sequence for ID
-- Defined in migration 20240915211603_inital_schema.sql.
ALTER TABLE "public"."subscription_tiers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."subscription_tiers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Primary Key
-- Defined in migration 20240915211603_inital_schema.sql.
ALTER TABLE ONLY "public"."subscription_tiers"
    ADD CONSTRAINT "subscription_tiers_pkey" PRIMARY KEY ("id");

-- Enable Row Level Security
-- Enabled in migration 20240915211603_inital_schema.sql.
ALTER TABLE "public"."subscription_tiers" ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- No specific RLS policies for "subscription_tiers" were explicitly defined in the migrations beyond enabling RLS.
-- Adding a common default policy for public read access, consistent with grants.
CREATE POLICY "Enable read access for all users" ON "public"."subscription_tiers"
    FOR SELECT USING (true);
-- INSERT, UPDATE, DELETE would typically be admin-only or managed by specific application logic.

-- Grant permissions
-- Grants from migration 20240915211603_inital_schema.sql.
GRANT ALL ON TABLE "public"."subscription_tiers" TO "anon";
GRANT ALL ON TABLE "public"."subscription_tiers" TO "authenticated";
GRANT ALL ON TABLE "public"."subscription_tiers" TO "service_role";

GRANT ALL ON SEQUENCE "public"."subscription_tiers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."subscription_tiers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."subscription_tiers_id_seq" TO "service_role";

-- Related function (from 20240915211603_inital_schema.sql)
-- This function retrieves the subscription tier for a given account.
CREATE OR REPLACE FUNCTION "public"."get_account_subscription"("p_account_id" bigint)
RETURNS "public"."subscription_tiers"
LANGUAGE "sql" STABLE SECURITY DEFINER
SET search_path = ''
AS $_$
    SELECT st.*
    FROM "public"."subscription_tiers" st
    JOIN "public"."accounts" a ON st.id = a.subscription_id
    WHERE a.id = p_account_id
    AND (p_account_id IN (SELECT "private"."get_member_accounts_for_user"(auth.email())));
$_$;

ALTER FUNCTION "public"."get_account_subscription"(bigint) OWNER TO "postgres";
GRANT EXECUTE ON FUNCTION "public"."get_account_subscription"(bigint) TO "anon", "authenticated", "service_role";

-- Comments on related entities:
-- The "public"."accounts" table has a foreign key ("subscription_id") referencing "public"."subscription_tiers"("id").
-- The "public"."subscriptions_chains_parameters" table (defined below or in a separate file) links subscription tiers to chain-specific parameters.


-- Table Definition: subscriptions_chains_parameters
-- Source: Created in migration 20250413025414_updated_accounts.sql
CREATE TABLE IF NOT EXISTS "public"."subscriptions_chains_parameters" (
    "subscription_id" bigint NOT NULL,
    "chain_id" "text" NOT NULL,
    "flat_fees" float NOT NULL DEFAULT 10,
    "sales_fees" float NOT NULL DEFAULT 0,
    "secondary_flat_fees" float NOT NULL DEFAULT 20,
    "secondary_sales_fees" float NOT NULL DEFAULT 0,
    "created_at" timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT "subscriptions_chains_parameters_pkey" PRIMARY KEY ("subscription_id", "chain_id")
);

-- Set ownership
ALTER TABLE "public"."subscriptions_chains_parameters" OWNER TO "postgres";

-- Foreign Keys
ALTER TABLE ONLY "public"."subscriptions_chains_parameters"
    ADD CONSTRAINT "subscriptions_chains_parameters_subscription_id_fkey" FOREIGN KEY ("subscription_id") REFERENCES "public"."subscription_tiers"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."subscriptions_chains_parameters"
    ADD CONSTRAINT "subscriptions_chains_parameters_chain_id_fkey" FOREIGN KEY ("chain_id") REFERENCES "public"."chains"("id") ON DELETE CASCADE;

-- Enable Row Level Security
-- RLS was not explicitly enabled for this table in the migration, but it's good practice if other tables have it.
ALTER TABLE "public"."subscriptions_chains_parameters" ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Adding a common default policy for public read access, consistent with grants.
CREATE POLICY "Enable read access for all users" ON "public"."subscriptions_chains_parameters"
    FOR SELECT USING (true);
-- INSERT, UPDATE, DELETE would typically be admin-only or managed by specific application logic.

-- Grant permissions
-- Grants from migration 20250413025414_updated_accounts.sql.
GRANT SELECT ON TABLE "public"."subscriptions_chains_parameters" TO "anon";
GRANT ALL ON TABLE "public"."subscriptions_chains_parameters" TO "authenticated";
GRANT ALL ON TABLE "public"."subscriptions_chains_parameters" TO "service_role";

-- Indexes
-- The primary key constraint automatically creates a unique index on ("subscription_id", "chain_id").
-- Additional indexes might be useful depending on query patterns, e.g., on "chain_id" if often queried alone.
CREATE INDEX IF NOT EXISTS "idx_subscriptions_chains_parameters_chain_id" ON "public"."subscriptions_chains_parameters" USING "btree" ("chain_id");
CREATE INDEX IF NOT EXISTS "idx_subscriptions_chains_parameters_subscription_id" ON "public"."subscriptions_chains_parameters" USING "btree" ("subscription_id");

